version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bbs_db
      MYSQL_USER: app_username
      MYSQL_PASSWORD: app_password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
  app:
    build: ./
    volumes:
      - ./:/src/2019techc/
    working_dir: /src/2019techc/
    ports:
      - 9000:9000
  web:
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./public/static/:/public/static/
